vim.cmd.colorscheme("gruvbuddy")

vim.api.nvim_set_hl(0, "StatusLine", { bg = "None" })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = "None" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#2f2f2f" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#ffff83", bg = "None" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "None" })
vim.api.nvim_set_hl(0, "Number", { fg = "#737373" })
vim.api.nvim_set_hl(0, "@number", { fg = "#737373" })
vim.api.nvim_set_hl(0, "Float", { fg = "#737373" })
local hl = vim.api.nvim_get_hl_by_name("Function", true)
vim.api.nvim_set_hl(0, "Function", { fg = hl.foreground, bold = true })
vim.api.nvim_set_hl(0, "@function", { fg = hl.foreground, bold = true })
