vim.cmd.colorscheme("retrobox")
vim.api.nvim_set_hl(0, "Normal", { fg="#ebdbb2", bg = "None" })
vim.api.nvim_set_hl(0, "NormalNC", { fg="#ebdbb2", bg = "None" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "None" })
vim.api.nvim_set_hl(0, "StatusLine", { fg="#62584e", bg = "None", bold = true })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg="#62584e", bg = "None" })
vim.api.nvim_set_hl(0, "Identifier", { fg="#ebdbb2", bg = "None" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg="#303030", bg = "None" })
