vim.cmd.colorscheme("retrobox")
vim.api.nvim_set_hl(0, "Normal", { bg = "#121212", fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#121212", fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "#121212", fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "StatusLine", { bg = "#202020", fg = "#ebdbb2", bold = true })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = "None", fg = "#404040", bold = true })
