vim.cmd.colorscheme("desert")
vim.api.nvim_set_hl(0, "Normal", { bg = "None" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "#202020", fg = "#dedede" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "None" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = "None" })
vim.api.nvim_set_hl(0, "StatusLine", { bg = "None", fg = "#edccb2", bold = true })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = "None", fg = "#edccb2" })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = "None", fg = "#606060" })
