vim.cmd.colorscheme("retrobox")
vim.api.nvim_set_hl(0, "Normal", { bg = "None", fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "None", fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "StatusLine", { bg = "#202020", fg = "#ebdbb2", bold = true })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = "#303030", fg = "#ebdbb2" })
-- vim.api.nvim_set_hl(0, "StatusLine", { bg = "#101010", fg = "#ebdbb2", bold = true })
-- vim.api.nvim_set_hl(0, "StatusLineNC", { bg = "#101010", fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = "None", fg = "#404040" })
