import = [
	"~/.config/alacritty/themes/rosepine.toml"
]

[keyboard]
bindings=[{ key = "c", mods = "Control", command = { program = "sh", args = ["-c", "kill -s SIGTERM $(pgrep -n -P $(ps -o ppid= -p $(ps -o sid= -p $$))"] } }]

[font]
normal = {family = 'Consolas Nerd Font'}
size = 12.5

[colors.primary]
background="#090909"
