import = [
	"~/.config/alacritty/themes/tokyonight.toml"
]

[keyboard]
bindings=[{ key = "c", mods = "Control", command = { program = "sh", args = ["-c", "kill -s SIGTERM $(pgrep -n -P $(ps -o ppid= -p $(ps -o sid= -p $$))"] } }]

[font]
normal = {family = 'JetBrainsMono NF'}
size = 11.0

[colors.primary]
background="#141414"
