# [general]
# import = [
#     "~/.config/alacritty/themes/themes/tokyo_night_bright.toml"
# ]

[font]
normal = {family = "JetBrainsMono Nerd Font"}
size = 12.5

[colors.primary]
background = "#050505"
