require("config.globals")
require("config.clear_cmdline")
require("config.statusline")

require("plugins.conform")
require("plugins.colorscheme")
require("plugins.devicons")
require("plugins.lsp")
require("plugins.oil")
require("plugins.snacks")
require("plugins.treesitter")
