require("config.globals")
require("config.clear_cmdline")
require("config.statusline")

require("plugins.conform")
require("plugins.devicons")
require("plugins.fzf-lua")
require("plugins.julia-vim")
require("plugins.lsp")
require("plugins.oil")
require("plugins.treesitter")
